drop table if exists stats;

create table if not exists stats (
    id bigint generated by default as identity primary key ,
    app varchar(20) not null ,
    uri varchar(50) not null ,
    ip varchar(20) not null ,
    timestamp timestamp not null
);