create table if not exists users (
    id bigint generated by default as identity primary key ,
    "name" varchar(30) not null ,
    email varchar(30) not null unique
);

create table if not exists categories (
    id bigint generated by default as identity primary key ,
    "name" varchar(20) not null unique
)